server:
  servlet:
    context-path: /grandmom

spring:
  application:
    name: grandmom

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  datasource:
    driver-class-name: ${db.driver-class-name}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  config:
    import: secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api
    disable-swagger-default-url: true
#    display-query-params-without-oauth2: true

openai:
  vision-url: https://api.openai.com/v1/chat/completions

internal-ai:
  access-url: http://223.130.131.239:38888

# Add JVM arguments
jvm:
  args: "--add-opens java.base/sun.security.ssl=ALL-UNNAMED"

oauth:
  kakao:
    client_id: ${oauth.kakao.client_id}
    redirect_uri: ${oauth.kakao.redirect_uri}
    admin_key: ${oauth.kakao.admin_key}